const assert=require('node:assert/strict');

const endpoint=process.env.CDP_ENDPOINT||'http://127.0.0.1:9223';
const pageUrl=process.env.PWA_URL||'http://127.0.0.1:8765/index.html';
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));

async function main(){
  const tabs=await fetch(`${endpoint}/json`).then(response=>response.json());
  const target=tabs.find(tab=>tab.type==='page'&&tab.url.startsWith(pageUrl));
  if(!target)throw new Error('PWA_BROWSER_TAB_NOT_FOUND');
  const socket=new WebSocket(target.webSocketDebuggerUrl),pending=new Map();let nextId=0;
  socket.onmessage=event=>{const message=JSON.parse(event.data);if(!message.id)return;const waiter=pending.get(message.id);if(!waiter)return;pending.delete(message.id);message.error?waiter.reject(new Error(message.error.message)):waiter.resolve(message.result)};
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject});
  const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}))});
  const evaluate=async expression=>{const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value};
  const reload=async()=>{await call('Page.reload',{ignoreCache:true});await delay(1400)};
  await call('Page.enable');await call('Runtime.enable');await reload();

  // Build a real V3 IndexedDB, then let the production V5 upgrade handler migrate it.
  await evaluate(`(async()=>{
    if(DB.db){DB.db.close();DB.db=null}
    await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(DB_NAME);r.onsuccess=resolve;r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('DELETE_BLOCKED'))});
    const oldStores=['app_meta','initialization_baseline','strategy_versions','investment_cycles','manual_trades','cash_pool_ledger','external_cashflows','calibration_snapshots','market_daily','trading_calendar','recommendations','todos','record_revisions','backup_history','settings'];
    await new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,3);r.onupgradeneeded=e=>{const db=e.target.result;for(const name of oldStores)db.createObjectStore(name,{keyPath:name==='market_daily'?'date':'id'})};r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,tx=db.transaction(oldStores,'readwrite'),now=new Date().toISOString();tx.objectStore('app_meta').put({id:'app',initialized:true,schemaVersion:3});tx.objectStore('initialization_baseline').put({id:'baseline',strategyStartDate:'2023-01-01',historicalExecutedCycles:171,historicalInvestedPrincipalCent:2138000,takeoverDate:today(),takeoverInMarketPrincipalCent:2138000,revisionStatus:'ORIGINAL',createdAt:now});tx.objectStore('strategy_versions').put({id:'strategy-v1.0',version:'1.0',effectiveFrom:today(),isCurrent:true,totalInvestmentBaseCent:15000000,targetPositionMinBp:1500,targetPositionMaxBp:1600,warningPositionBp:1800,slowdownPositionBp:1900,baseHardLimitBp:2000,baseHardLimitCent:3000000,annualHardLimitIncrementCent:600000,baseRecurringAmountCent:10000,targetXirrBp:600,minHoldingYears:3,maxHoldingYears:5,createdAt:now});tx.objectStore('external_cashflows').put({id:'opening',date:today(),type:'TAKEOVER_OPENING',amountCent:-2138000});tx.objectStore('calibration_snapshots').put({id:'old-cal',snapshotDate:today(),snapshotAt:now,fundMarketValueCent:2164700,totalSharesMicro:10000000000,source:'INITIALIZATION',createdAt:now});tx.objectStore('investment_cycles').put({id:'old-executed',scheduledDate:today(),status:'EXECUTED',actualAmountCent:10000,createdAt:now});tx.objectStore('manual_trades').put({id:'old-not',type:'MANUAL_BUY',tradeDate:today(),status:'NOT_EXECUTED',amountCent:0,createdAt:now});tx.objectStore('record_revisions').put({id:'old-revision',entityType:'investment_cycle',entityId:'old-executed',fieldName:'actualAmountCent',before:5000,after:10000,changedAt:now});tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)}});
    return true;
  })()`);
  await reload();
  const migration=await evaluate(`(async()=>{const db=await DB.open(),executed=await DB.get('investment_cycles','old-executed'),notExecuted=await DB.get('manual_trades','old-not'),cal=await DB.get('calibration_snapshots','old-cal'),app=await DB.get('app_meta','app');return {version:db.version,stores:[...db.objectStoreNames],executedShare:executed.shareConfirmationStatus,executedAmount:executed.actualAmountCent,notExecutedShare:notExecuted.shareConfirmationStatus,anchor:cal.isShareAnchor,anchorShares:cal.anchorSharesMicro,appSchema:app.schemaVersion,revision:!!await DB.get('record_revisions','old-revision'),principal:(await Calc.metrics()).principal,policyCount:(await DB.all('take_profit_policy_versions')).length,baselineCount:(await DB.all('take_profit_baselines')).length,eventCount:(await DB.all('take_profit_events')).length}})()`);
  assert.equal(migration.version,5);assert.ok(migration.stores.includes('fund_profiles'));assert.ok(migration.stores.includes('fund_nav_daily'));assert.ok(migration.stores.includes('share_confirmation_events'));assert.ok(migration.stores.includes('take_profit_policy_versions'));assert.ok(migration.stores.includes('take_profit_baselines'));assert.ok(migration.stores.includes('take_profit_events'));assert.equal(migration.executedShare,'PENDING_NAV');assert.equal(migration.executedAmount,10000);assert.equal(migration.notExecutedShare,'NOT_APPLICABLE');assert.equal(migration.anchor,true);assert.equal(migration.anchorShares,10000000000);assert.equal(migration.appSchema,5);assert.equal(migration.revision,true);assert.equal(migration.principal,2148000);assert.equal(migration.policyCount,1);assert.equal(migration.baselineCount,0);assert.equal(migration.eventCount,0);

  // Reset only the isolated browser profile and exercise a fresh V1.0.11 workflow.
  await evaluate(`(async()=>{if(DB.db){DB.db.close();DB.db=null}await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(DB_NAME);r.onsuccess=resolve;r.onerror=()=>reject(r.error)});return true})()`);
  await reload();
  const workflow=await evaluate(`(async()=>{
    const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));window.alert=()=>{};window.confirm=()=>true;
    $('initMarketValue').value='21647';$('initShares').value='10000';$('initPrincipal').value='21380';$('initStartDate').value='2023-01-01';$('initCycles').value='171';await App.initialize();const takeover=addDays(today(),-29),opening=await DB.get('external_cashflows','opening'),baseline=await DB.get('initialization_baseline','baseline');await DB.put('external_cashflows',{...opening,date:takeover});await DB.put('initialization_baseline',{...baseline,takeoverDate:takeover});
    App.showPage('fund-nav');await wait(200);App.openFundProfile(null);$('fpCode').value='999999';$('fpName').value='浏览器隔离测试基金';$('fpEffective').value=today();$('fpReason').value='V1.0.11浏览器隔离测试';await App.saveFundProfile();
    const date=today(),nextPendingDate=addDays(date,1),strategy=await App.strategyForDate(date),pendingOne=await App.ensurePendingCycle(date,strategy),pendingTwo=await App.ensurePendingCycle(nextPendingDate,strategy);await App.refreshAll();const todoBefore=$('todoList').textContent;App.openPendingRecords();await wait(200);const pendingBeforeText=$('recordsList').textContent,pendingBeforeCount=$('recordsList').querySelectorAll('.item').length;await App.savePendingAction(pendingOne,'investment_cycle','EXECUTED',15000,'浏览器回归：确认150元');const todoAfterOne=$('todoList').textContent;await App.savePendingAction(pendingTwo,'investment_cycle','NOT_EXECUTED',0,'浏览器回归：本期未执行');const todoAfterAll=$('todoList').textContent;App.openPendingRecords();await wait(200);const pendingAfterText=$('recordsList').textContent;
    const initialRecord=await DB.get('investment_cycles','cycle-'+date),notExecuted=await DB.get('investment_cycles','cycle-'+nextPendingDate),initialMetrics=await Calc.metrics();
    App.openRecordEdit(initialRecord,'investment_cycle');$('erActual').value='600';$('erCash').value='0';$('erExternal').value='600';$('erReason').value='浏览器回归：实际成交600元';await App.saveRecordEdit(initialRecord,'investment_cycle');
    const modified=await DB.get('investment_cycles','cycle-'+date),modifiedMetrics=await Calc.metrics();
    const nextDate=addDays(date,1),profile=await Fund.profile(date),now=new Date().toISOString();
    const nextNav={id:'999999-'+nextDate,fundCode:'999999',fundProfileId:profile.id,navDate:nextDate,unitNavScaled:1260000,source:'MANUAL',recordedAt:now,revisionStatus:'ORIGINAL',voided:false,createdAt:now};await DB.put('fund_nav_daily',nextNav);await Fund.confirmPendingForNav(nextNav);const afterT1=await DB.get('investment_cycles','cycle-'+date);
    const nav={id:'999999-'+date,fundCode:'999999',fundProfileId:profile.id,navDate:date,unitNavScaled:1250000,source:'MANUAL',recordedAt:now,revisionStatus:'ORIGINAL',voided:false,createdAt:now},updates=await Fund.prepareUpdatesForNav(nav,false,now);await DB.atomic(['fund_nav_daily','investment_cycles','manual_trades','share_confirmation_events'],tx=>{tx.objectStore('fund_nav_daily').put(nav);for(const x of updates.cycleUpdates)tx.objectStore('investment_cycles').put(x);for(const x of updates.tradeUpdates)tx.objectStore('manual_trades').put(x);for(const x of updates.events)tx.objectStore('share_confirmation_events').put(x)});
    const confirmed=await DB.get('investment_cycles','cycle-'+date),confirmedMetrics=await Calc.metrics();
    const correctedAt=new Date(Date.now()+1000).toISOString(),correctedNav={...nav,unitNavScaled:1000000,source:'MANUAL_CORRECTED',revisionStatus:'MODIFIED',modifiedAt:correctedAt,changeReason:'浏览器回归：修正净值'},correctedUpdates=await Fund.prepareUpdatesForNav(correctedNav,true,correctedAt),revision={id:'rev-nav-test',entityType:'fund_nav',entityId:nav.id,fieldName:'unitNavScaled',fieldLabel:'基金单位净值',before:1250000,after:1000000,changedAt:correctedAt,changeReason:'浏览器回归：修正净值',source:'USER_EDIT'};await DB.atomic(['fund_nav_daily','investment_cycles','manual_trades','share_confirmation_events','record_revisions'],tx=>{tx.objectStore('fund_nav_daily').put(correctedNav);for(const x of correctedUpdates.cycleUpdates)tx.objectStore('investment_cycles').put(x);for(const x of correctedUpdates.tradeUpdates)tx.objectStore('manual_trades').put(x);for(const x of correctedUpdates.events)tx.objectStore('share_confirmation_events').put(x);tx.objectStore('record_revisions').put(revision)});
    const corrected=await DB.get('investment_cycles','cycle-'+date),correctedMetrics=await Calc.metrics(),confirmedEvents=await DB.all('share_confirmation_events');
    $('cMarketValue').value='10500';$('cShares').value='10550';$('cReason').value='浏览器回归：真实账户校准';await App.calibrate();const calibrationMetrics=await Calc.metrics(),calibration=calibrationMetrics.cal;
    App.showPage('records');await wait(200);const recordsText=$('recordsList').textContent;App.showPage('fund-basis');await wait(200);const basisText=$('fundBasisContent').textContent;App.showPage('share-timeline');await wait(200);const shareTimelineText=$('shareTimelineContent').textContent;App.showPage('simulation-basis');await wait(200);const simulationBasisText=$('simulationBasisContent').textContent;App.showPage('calibration-history');await wait(200);const calibrationHistoryText=$('page-calibration-history').textContent;App.openCalibration('calibration-history');await wait(50);const calibrationRoute=!$('page-more').classList.contains('hidden')&&document.activeElement===$('cMarketValue');App.showPage('analysis');await wait(200);const analysisText=$('page-analysis').textContent;
    const exported={schemaVersion:3,stores:{}};for(const store of STORES)exported.stores[store]=await DB.all(store);const beforeCounts={profiles:exported.stores.fund_profiles.length,navs:exported.stores.fund_nav_daily.length,events:exported.stores.share_confirmation_events.length,revisions:exported.stores.record_revisions.length};await DB.atomic(['fund_profiles','fund_nav_daily','share_confirmation_events','record_revisions'],tx=>{for(const store of ['fund_profiles','fund_nav_daily','share_confirmation_events','record_revisions'])tx.objectStore(store).clear()});const normalized=FundShareCore.normalizeBackupStores(exported,STORES);await DB.atomic(STORES,tx=>{for(const store of STORES){const target=tx.objectStore(store);target.clear();for(const row of normalized[store])target.put(row)}});const afterCounts={profiles:(await DB.all('fund_profiles')).length,navs:(await DB.all('fund_nav_daily')).length,events:(await DB.all('share_confirmation_events')).length,revisions:(await DB.all('record_revisions')).length};
    return {version:$('headerSub').textContent,databaseVersion:(await DB.open()).version,todoBefore,pendingBeforeText,pendingBeforeCount,todoAfterOne,todoAfterAll,pendingAfterText,initialActual:initialRecord.actualAmountCent,initialManualExtra:initialRecord.manualExtraAmountCent,initialShare:initialRecord.shareConfirmationStatus,initialPrincipal:initialMetrics.principal,initialCycles:initialMetrics.breakdown.effectiveCycleCount,notExecutedStatus:notExecuted.executionStatus,notExecutedActual:notExecuted.actualAmountCent,notExecutedShare:notExecuted.shareConfirmationStatus,pendingAudit:(await DB.all('record_revisions')).filter(x=>x.changeType==='EXECUTION_CONFIRMATION').length,modifiedShare:modified.shareConfirmationStatus,modifiedPrincipal:modifiedMetrics.principal,modifiedCycles:modifiedMetrics.breakdown.effectiveCycleCount,modifiedRevision:modified.revisionStatus,afterT1:afterT1.shareConfirmationStatus,confirmedStatus:confirmed.shareConfirmationStatus,confirmedShares:confirmed.confirmedSharesMicro,confirmedDerived:confirmedMetrics.fundMetrics.derived.derivedSharesMicro,correctedStatus:corrected.shareConfirmationStatus,correctedShares:corrected.confirmedSharesMicro,correctedDerived:correctedMetrics.fundMetrics.derived.derivedSharesMicro,realFund:correctedMetrics.fund,simulatedFund:correctedMetrics.simulatedFund,formalXirr:correctedMetrics.xirr,simulatedXirr:correctedMetrics.simulatedXirr,periodReturnStatus:calibrationMetrics.periodReturn.status,periodReturn:calibrationMetrics.periodReturn.rate,shortTakeover:calibrationMetrics.periodReturn.shortTakeover,calibrationAnchor:calibration.anchorSharesMicro,calibrationBefore:calibration.derivedSharesBeforeCalibrationMicro,calibrationCorrection:calibration.shareCorrectionMicro,calibrationReal:calibrationMetrics.fund,postCalibrationDerived:calibrationMetrics.fundMetrics.derived.derivedSharesMicro,eventCount:confirmedEvents.length,navRevision:!!await DB.get('record_revisions','rev-nav-test'),recordsText,basisText,shareTimelineText,simulationBasisText,calibrationHistoryText,calibrationRoute,analysisText,beforeCounts,afterCounts}
  })()`);
  assert.match(workflow.version,/V1\.0\.11/);assert.equal(workflow.databaseVersion,5);assert.match(workflow.todoBefore,/待执行确认 2 期/);assert.equal(workflow.pendingBeforeCount,2);assert.doesNotMatch(workflow.pendingBeforeText,/待净值确认/);assert.match(workflow.todoAfterOne,/待执行确认 1 期/);assert.doesNotMatch(workflow.todoAfterAll,/待执行确认/);assert.match(workflow.pendingAfterText,/当前没有待执行记录/);assert.equal(workflow.initialActual,15000);assert.equal(workflow.initialManualExtra,5000);assert.equal(workflow.initialShare,'PENDING_NAV');assert.equal(workflow.initialPrincipal,2153000);assert.equal(workflow.initialCycles,172);assert.equal(workflow.notExecutedStatus,'NOT_EXECUTED');assert.equal(workflow.notExecutedActual,0);assert.equal(workflow.notExecutedShare,'NOT_APPLICABLE');assert.equal(workflow.pendingAudit,2);assert.equal(workflow.modifiedShare,'PENDING_NAV');assert.equal(workflow.modifiedPrincipal,2198000);assert.equal(workflow.modifiedCycles,172);assert.equal(workflow.modifiedRevision,'MODIFIED');assert.equal(workflow.afterT1,'PENDING_NAV');assert.equal(workflow.confirmedStatus,'CONFIRMED');assert.equal(workflow.confirmedShares,480000000);assert.equal(workflow.confirmedDerived,10480000000);assert.equal(workflow.correctedStatus,'MANUAL_CORRECTED');assert.equal(workflow.correctedShares,600000000);assert.equal(workflow.correctedDerived,10600000000);assert.equal(workflow.realFund,2164700);assert.equal(workflow.simulatedFund,1060000);assert.notEqual(workflow.formalXirr,workflow.simulatedXirr);assert.equal(workflow.periodReturnStatus,'AVAILABLE');assert.equal(workflow.shortTakeover,true);assert.ok(Number.isFinite(workflow.periodReturn));assert.equal(workflow.calibrationAnchor,10550000000);assert.equal(workflow.calibrationBefore,10600000000);assert.equal(workflow.calibrationCorrection,-50000000);assert.equal(workflow.calibrationReal,1050000);assert.equal(workflow.postCalibrationDerived,10550000000);assert.ok(workflow.eventCount>=2);assert.equal(workflow.navRevision,true);assert.match(workflow.recordsText,/已执行/);assert.match(workflow.recordsText,/已修改/);assert.match(workflow.recordsText,/人工修正确认/);assert.match(workflow.basisText,/最近真实校准市值/);assert.match(workflow.basisText,/当前自动模拟市值/);assert.match(workflow.basisText,/正式XIRR/);assert.match(workflow.basisText,/模拟XIRR/);assert.match(workflow.shareTimelineText,/递推份额变化明细/);assert.match(workflow.shareTimelineText,/人工校准锚点/);assert.match(workflow.simulationBasisText,/模拟市值依据/);assert.match(workflow.simulationBasisText,/当前递推份额 × 最新有效基金单位净值/);assert.match(workflow.simulationBasisText,/并非基金账户真实余额/);assert.match(workflow.calibrationHistoryText,/\+ 新增校准/);assert.equal(workflow.calibrationRoute,true);assert.match(workflow.analysisText,/正式接管后策略XIRR/);assert.match(workflow.analysisText,/模拟接管后策略XIRR/);assert.match(workflow.analysisText,/接管后区间收益率/);assert.match(workflow.analysisText,/接管期较短/);assert.deepEqual(workflow.afterCounts,workflow.beforeCounts);

  const market=await evaluate(`(async()=>{const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));App.showPage('analysis');await wait(200);$('btnMarketRefresh').click();await wait(15000);return {point:$('realtimePoint').textContent,source:$('realtimeSource').textContent,close:$('marketClose').textContent,result:$('marketUpdateResult').textContent,separated:[...document.querySelectorAll('.notice')].some(node=>node.textContent.includes('不作为策略计算依据'))}})()`);
  assert.notEqual(market.close,'—');assert.equal(market.separated,true);if(market.point!=='—')assert.match(market.source,/MANUAL_DIRECT_REALTIME/);else assert.match(market.result,/实时指数不可用/);
  await call('Network.enable');await evaluate(`navigator.serviceWorker.ready.then(()=>true)`);await call('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0,connectionType:'none'});await call('Page.reload');await delay(1600);const offline=await evaluate(`(async()=>({version:$('headerSub')?.textContent||'',principal:(await Calc.metrics()).principal,controlled:!!navigator.serviceWorker.controller}))()`);await call('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1,connectionType:'none'});socket.close();assert.match(offline.version,/V1\.0\.11/);assert.equal(offline.principal,2198000);assert.equal(offline.controlled,true);
  console.log(JSON.stringify({migration,workflow,market,offline},null,2));
}

main().catch(error=>{console.error(error);process.exitCode=1});
